// ============================================================
// LISTES DE VOCABULAIRE
// ============================================================
// Pour ajouter une nouvelle liste : copiez un bloc { id, title, words }
// et remplissez avec vos propres mots. "id" doit être unique (pas d'espace/accent).
// Chaque mot est un objet { en: "...", fr: "..." }.
// ============================================================

const VOCAB_LISTS = [
  {
    id: "redaction-essai",
    title: "La rédaction d'un essai",
    words: [
      { en: "An essay", fr: "Un essai" },
      { en: "A paper", fr: "Un article universitaire" },
      { en: "A draft", fr: "Un premier jet" },
      { en: "A central question", fr: "Une problématique" },
      { en: "A topic", fr: "Un sujet" },
      { en: "An issue", fr: "Une question, un problème" },
      { en: "The field of study", fr: "Le domaine d'étude" },
      { en: "The plan / the outline", fr: "Le plan" },
      { en: "The premise", fr: "Le postulat de départ" },
      { en: "A statement / a claim", fr: "Une affirmation" },
      { en: "The thesis", fr: "La thèse, la proposition à démontrer" },
      { en: "The thesis statement", fr: "L'énoncé de la thèse" },
      { en: "A quotation / a quote", fr: "Une citation" },
      { en: "Inverted commas / quotation marks", fr: "Des guillemets" },
      { en: "An excerpt (from)", fr: "Un extrait (de)" },
      { en: "A paragraph", fr: "Un paragraphe" },
      { en: "The body", fr: "Le corps de l'essai" },
      { en: "A rebuttal", fr: "Une réfutation" },
      { en: "Academia", fr: "Le monde universitaire" },
      { en: "Academic English", fr: "L'anglais académique / universitaire" }
    ]
  },
  {
    id: "transmission-information",
    title: "La transmission de l'information",
    words: [
      { en: "The meaning", fr: "Le sens" },
      { en: "The content", fr: "Le contenu" },
      { en: "Criticism", fr: "La critique" },
      { en: "A critic", fr: "Un critique" },
      { en: "A lecture", fr: "Une conférence, un cours magistral" },
      { en: "A speech", fr: "Un discours" },
      { en: "A review", fr: "Un compte-rendu, une analyse" },
      { en: "A journal", fr: "Une revue universitaire" },
      { en: "The literature on", fr: "Les livres et articles écrits sur..." },
      { en: "A thinker", fr: "Un penseur" },
      { en: "A theorist", fr: "Un théoricien" },
      { en: "A scholar", fr: "Un intellectuel" },
      { en: "A response", fr: "Une réponse, une réaction" },
      { en: "Feedback", fr: "Un retour" },
      { en: "Advice / a tip", fr: "Un conseil" },
      { en: "A warning", fr: "Un avertissement" },
      { en: "A summary", fr: "Un résumé" },
      { en: "A ratio", fr: "Une proportion, un rapport" },
      { en: "A translation", fr: "Une traduction" },
      { en: "The epitome", fr: "L'incarnation" }
    ]
  },
  {
    id: "presse",
    title: "La presse",
    words: [
      { en: "The news", fr: "L'actualité" },
      { en: "The mainstream media / the legacy media", fr: "Les média traditionnels" },
      { en: "A correspondent", fr: "Un correspondant" },
      { en: "A reporter", fr: "Un envoyé spécial" },
      { en: "An anchorman/anchorwoman (US), a presenter", fr: "Un présentateur" },
      { en: "A host", fr: "Un animateur" },
      { en: "A guest", fr: "Un invité" },
      { en: "A speaker / a contributor", fr: "Un intervenant" },
      { en: "An editorial policy", fr: "Une ligne éditoriale" },
      { en: "A newspaper", fr: "Un journal" },
      { en: "A broadsheet", fr: "Un journal de qualité" },
      { en: "A tabloid", fr: "Un tabloïd" },
      { en: "A report", fr: "Un reportage" },
      { en: "A broadcast / a show", fr: "Une émission" },
      { en: "A talkshow", fr: "Une émission de débats" },
      { en: "A recording", fr: "Un enregistrement" },
      { en: "The viewers", fr: "Les téléspectateurs" },
      { en: "The listeners", fr: "Les auditeurs" },
      { en: "Audience rating", fr: "L'audimat" },
      { en: "The readership", fr: "Le lectorat" }
    ]
  },
  {
    id: "opinions-croyances",
    title: "Les opinions et croyances",
    words: [
      { en: "Faith", fr: "La foi" },
      { en: "Trust", fr: "La confiance" },
      { en: "A belief", fr: "Une croyance" },
      { en: "A believer", fr: "Un croyant" },
      { en: "A bias", fr: "Un parti pris" },
      { en: "A pilgrimage", fr: "Un pèlerinage" },
      { en: "Mass", fr: "La messe" },
      { en: "The Scriptures", fr: "Les Saintes Ecritures, la Bible" },
      { en: "The Gospel", fr: "L'Evangile" },
      { en: "A sin", fr: "Un péché" },
      { en: "A vice", fr: "Un vice" },
      { en: "A virtue", fr: "Une vertu" },
      { en: "Righteousness", fr: "La rectitude, la vertu" },
      { en: "Denial", fr: "Le déni" },
      { en: "A bigot", fr: "Un bigot, un sectaire" },
      { en: "An assumption", fr: "Une supposition" },
      { en: "Political correctness", fr: "Le politiquement correct" },
      { en: "Censorship", fr: "La censure" },
      { en: "Secularism", fr: "La laïcité" },
      { en: "A curse", fr: "Une malédiction" }
    ]
  },
  {
    id: "conditions-de-vie",
    title: "Les conditions de vie",
    words: [
      { en: "Needs", fr: "Les besoins" },
      { en: "Living standards", fr: "Le niveau de vie" },
      { en: "Housing", fr: "Le logement" },
      { en: "Income", fr: "Les revenus" },
      { en: "Health", fr: "La santé" },
      { en: "Safety", fr: "La sécurité" },
      { en: "The neighborhood", fr: "Le quartier" },
      { en: "Transportation", fr: "Les moyens de transport" },
      { en: "Amenities", fr: "L'équipement, les infrastructures" },
      { en: "Sanitation", fr: "L'hygiène publique, l'assainissement" },
      { en: "Heating", fr: "Le chauffage" },
      { en: "Comfort", fr: "Le confort" },
      { en: "Affordability", fr: "L'accessibilité (financière)" },
      { en: "The poverty line", fr: "Le seuil de pauvreté" },
      { en: "Life expectancy", fr: "L'espérance de vie" },
      { en: "A homeless person", fr: "Un SDF" },
      { en: "Illiteracy", fr: "L'illettrisme" },
      { en: "A beggar", fr: "Un mendiant" },
      { en: "Unemployment", fr: "Le chômage" }
    ]
  },
  {
    id: "lien-social",
    title: "Le lien social",
    words: [
      { en: "Assistance", fr: "L'aide, l'assistance" },
      { en: "Relief", fr: "L'aide humanitaire" },
      { en: "Benefits", fr: "Les allocations" },
      { en: "Contributions", fr: "Les cotisations" },
      { en: "The welfare state", fr: "L'état providence" },
      { en: "Asylum", fr: "L'asile" },
      { en: "Diversity", fr: "La mixité" },
      { en: "A disability", fr: "Un handicap" },
      { en: "The elderly", fr: "Les personnes âgées" },
      { en: "Retirement", fr: "La retraite" },
      { en: "A pension", fr: "Une retraite" },
      { en: "The youth", fr: "Les jeunes" },
      { en: "Day care", fr: "Une crèche" },
      { en: "A nuclear family", fr: "Une famille nucléaire" },
      { en: "A single-parent family", fr: "Une famille monoparentale" },
      { en: "A relative", fr: "Un membre de la famille" },
      { en: "A charity", fr: "Une association caritative" },
      { en: "A food bank", fr: "Une banque alimentaire" },
      { en: "The soup kitchen", fr: "La soupe populaire" },
      { en: "A food stamp", fr: "Un bon alimentaire" }
    ]
  },
  {
    id: "conflit-social",
    title: "Le conflit social et les revendications",
    words: [
      { en: "Social unrest", fr: "L'agitation sociale" },
      { en: "An uproar / an outcry", fr: "Un tollé" },
      { en: "Protest", fr: "La contestation" },
      { en: "A demonstration", fr: "Une manifestation" },
      { en: "A strike", fr: "Une grève" },
      { en: "A hunger strike", fr: "Une grève de la faim" },
      { en: "A riot", fr: "Une émeute" },
      { en: "Looting", fr: "Le pillage" },
      { en: "An uprising", fr: "Un soulèvement" },
      { en: "A mob", fr: "Une foule" },
      { en: "A confrontation / a clash", fr: "Un affrontement" },
      { en: "An activist", fr: "Un activiste" },
      { en: "Militancy", fr: "Le militantisme" },
      { en: "A demand / a claim", fr: "Une revendication" },
      { en: "Pressure", fr: "La pression" },
      { en: "A curfew", fr: "Un couvre-feu" },
      { en: "A sit-in", fr: "Une occupation" },
      { en: "A rally", fr: "Un rassemblement" },
      { en: "A troublemaker", fr: "Un fauteur de troubles" },
      { en: "Tear gas", fr: "Le gaz lacrymogène" }
    ]
  },
  {
    id: "education",
    title: "L'éducation",
    words: [
      { en: "Upbringing / education", fr: "L'éducation" },
      { en: "The background", fr: "Le milieu d'origine" },
      { en: "The cultural capital", fr: "Le capital culturel" },
      { en: "General knowledge", fr: "La culture générale" },
      { en: "A course", fr: "Un cours" },
      { en: "A subject", fr: "Une matière" },
      { en: "An assignment", fr: "Un devoir" },
      { en: "A mark / a grade (US)", fr: "Une note" },
      { en: "A textbook", fr: "Un manuel scolaire" },
      { en: "The curriculum", fr: "Le programme" },
      { en: "A degree / a diploma", fr: "Un diplôme" },
      { en: "A graduate", fr: "Quelqu'un qui est diplômé" },
      { en: "A scholarship / a grant / a bursary", fr: "Une bourse" },
      { en: "A skill", fr: "Une compétence" },
      { en: "A boarding school", fr: "Un internat" },
      { en: "An intern / a trainee", fr: "Un stagiaire" },
      { en: "A professor", fr: "Un prof d'université" },
      { en: "College (US)", fr: "Université" },
      { en: "School fees / tuition fees", fr: "Les frais de scolarité" },
      { en: "An alumnus", fr: "Un ancien élève" }
    ]
  },
  {
    id: "difficultes",
    title: "Les difficultés",
    words: [
      { en: "Pain", fr: "La douleur" },
      { en: "Harm", fr: "Le tort" },
      { en: "Damage", fr: "Des dommages, des dégâts" },
      { en: "Hardship", fr: "L'adversité" },
      { en: "A struggle", fr: "Une lutte" },
      { en: "Suffering", fr: "La souffrance" },
      { en: "Misfortune", fr: "La malchance" },
      { en: "Distress", fr: "Le désarroi" },
      { en: "Deprivation", fr: "La déprivation" },
      { en: "An ordeal", fr: "Une épreuve" },
      { en: "Grief", fr: "Le chagrin" },
      { en: "A challenge", fr: "Un défi" },
      { en: "A setback", fr: "Un revers, un contretemps" },
      { en: "A hazard / a jeopardy", fr: "Un danger" },
      { en: "A burden", fr: "Un fardeau" },
      { en: "The yoke", fr: "Le joug" },
      { en: "Bullying / harassment", fr: "Le harcèlement" },
      { en: "A trauma", fr: "Un traumatisme" },
      { en: "A nightmare", fr: "Un cauchemar" },
      { en: "A conundrum", fr: "Un problème difficile, un casse-tête" }
    ]
  },
  {
    id: "recherche-solutions",
    title: "La recherche de solutions",
    words: [
      { en: "An advocate / a proponent", fr: "Un défenseur, un partisan" },
      { en: "An opponent / a detractor", fr: "Un détracteur" },
      { en: "A requirement", fr: "Un prérequis, une condition nécessaire" },
      { en: "A situation", fr: "Une situation problématique" },
      { en: "A loophole", fr: "Une faille, un échappatoire" },
      { en: "An agenda", fr: "Un programme, des choses que l'on souhaite faire" },
      { en: "A volunteer", fr: "Un bénévole" },
      { en: "A motive", fr: "Un motif, un mobile" },
      { en: "A stroke of luck", fr: "Un coup de chance" },
      { en: "An attempt", fr: "Une tentative" },
      { en: "An experiment", fr: "Une expérience" },
      { en: "The triggering factor", fr: "Le facteur déclencheur" },
      { en: "The will", fr: "La volonté" },
      { en: "The driving force", fr: "L'énergie motrice" },
      { en: "The impetus", fr: "L'impulsion" },
      { en: "The momentum", fr: "L'élan" }
    ]
  },
  {
    id: "negociation-decisions",
    title: "La négociation et les décisions",
    words: [
      { en: "A wish", fr: "Un souhait" },
      { en: "An offer", fr: "Une offre" },
      { en: "Bargaining", fr: "La négociation" },
      { en: "A deal / an agreement", fr: "Un accord" },
      { en: "A compromise / a trade-off", fr: "Un compromis" },
      { en: "Talks", fr: "Des négociations" },
      { en: "Leverage", fr: "Un levier" },
      { en: "The 2 sides", fr: "Les deux camps" },
      { en: "The outcome", fr: "Le résultat, l'issue" },
      { en: "A deadlock", fr: "Une impasse" },
      { en: "A request", fr: "Une demande" },
      { en: "A grievance", fr: "Un grief, une doléance" },
      { en: "The stakes", fr: "Les enjeux" },
      { en: "A truce", fr: "Une trêve" },
      { en: "Blackmail", fr: "Le chantage" },
      { en: "An apology", fr: "Des excuses" },
      { en: "Forgiveness", fr: "Le pardon" },
      { en: "An oath", fr: "Un serment" },
      { en: "A pledge", fr: "Une promesse, un engagement" }
    ]
  },
  {
    id: "monde-entreprise",
    title: "Le monde de l'entreprise",
    words: [
      { en: "A company / a firm", fr: "Une entreprise" },
      { en: "Business", fr: "Les affaires" },
      { en: "The market", fr: "Le marché" },
      { en: "A customer", fr: "Un client" },
      { en: "Revenue", fr: "Les recettes, les revenus" },
      { en: "The sales", fr: "Les ventes" },
      { en: "The CEO", fr: "Le PDG" },
      { en: "An executive", fr: "Un cadre" },
      { en: "The board", fr: "Le conseil d'administration" },
      { en: "The headquarters", fr: "Le siège" },
      { en: "An office", fr: "Un bureau" },
      { en: "Assets", fr: "L'actif, le capital, les atouts" },
      { en: "Liabilities", fr: "Le passif, les dettes" },
      { en: "The output", fr: "Le rendement" },
      { en: "Share / stock", fr: "Une action" },
      { en: "A shareholder", fr: "Un actionnaire" },
      { en: "A stakeholder", fr: "Une partie prenante" },
      { en: "A supplier", fr: "Un fournisseur" },
      { en: "A brand", fr: "Une marque" },
      { en: "A trade union", fr: "Un syndicat" }
    ]
  },
  {
    id: "economie",
    title: "L'économie",
    words: [
      { en: "Growth", fr: "La croissance" },
      { en: "Wealth", fr: "La richesse" },
      { en: "A debt", fr: "Une dette" },
      { en: "A subsidy", fr: "Une subvention" },
      { en: "A tax", fr: "Un impôt" },
      { en: "A tariff", fr: "Un droit de douane" },
      { en: "The taxpayer", fr: "Le contribuable" },
      { en: "A currency", fr: "Une devise" },
      { en: "Trade", fr: "Le commerce" },
      { en: "Investment", fr: "L'investissement" },
      { en: "The labor market / job market", fr: "Le marché du travail" },
      { en: "The workforce / manpower", fr: "La main d'oeuvre" },
      { en: "GDP (Gross Domestic Product)", fr: "PIB" },
      { en: "A business sector / an industry", fr: "Un secteur d'activité" },
      { en: "Consumption", fr: "La consommation" },
      { en: "Competition", fr: "La concurrence" },
      { en: "A household", fr: "Un foyer" },
      { en: "Oil", fr: "Le pétrole" },
      { en: "Gas", fr: "L'essence" }
    ]
  },
  {
    id: "pouvoir",
    title: "Le pouvoir",
    words: [
      { en: "A regime", fr: "Un régime" },
      { en: "Authoritarianism", fr: "L'autoritarisme" },
      { en: "Totalitarianism", fr: "Le totalitarisme" },
      { en: "A dictatorship", fr: "Une dictature" },
      { en: "Slavery", fr: "L'esclavage" },
      { en: "A coup", fr: "Un coup d'état" },
      { en: "The political spectrum", fr: "L'échiquier politique" },
      { en: "Politics", fr: "La politique" },
      { en: "A policy", fr: "Une mesure, une politique" },
      { en: "A politician", fr: "Un homme politique" },
      { en: "A legislator / a lawmaker", fr: "Un législateur" },
      { en: "A representative", fr: "Un représentant" },
      { en: "Abuse of power", fr: "Abus de pouvoir" },
      { en: "The head of state", fr: "Le chef d'état" },
      { en: "An advisor", fr: "Un conseiller" },
      { en: "A minister / a secretary", fr: "Un ministre" },
      { en: "A civil servant", fr: "Un fonctionnaire" },
      { en: "A term", fr: "Un mandat" },
      { en: "Legitimacy", fr: "La légitimité" },
      { en: "A sovereign power", fr: "Un pouvoir régalien" }
    ]
  },
  {
    id: "ambition-succes-echec",
    title: "L'ambition, le succès et l'échec",
    words: [
      { en: "A goal / a purpose", fr: "Un but" },
      { en: "A target", fr: "Une cible" },
      { en: "An incentive", fr: "Un avantage qui motive" },
      { en: "A deterrent", fr: "Un frein, un élément qui démotive" },
      { en: "An achievement / an accomplishment", fr: "Une réussite" },
      { en: "Success", fr: "Le succès" },
      { en: "A feat", fr: "Une prouesse" },
      { en: "A reward", fr: "Une récompense" },
      { en: "A failure", fr: "Un échec" },
      { en: "A disappointment", fr: "Une déception" },
      { en: "A mistake", fr: "Une erreur" },
      { en: "A blunder", fr: "Une gaffe" },
      { en: "Commitment", fr: "L'engagement" },
      { en: "Involvement", fr: "L'implication" },
      { en: "The social ladder", fr: "L'échelle sociale" },
      { en: "An expectation", fr: "Une attente" },
      { en: "A loss", fr: "Une perte" },
      { en: "Mourning", fr: "Le deuil" },
      { en: "A backlash", fr: "Un contrecoup, un retour de bâton" },
      { en: "A side effect", fr: "Un effet secondaire" }
    ]
  },
  {
    id: "progres",
    title: "Le progrès",
    words: [
      { en: "Progress", fr: "Le progrès" },
      { en: "A change / a shift", fr: "Un changement" },
      { en: "A breakthrough", fr: "Une percée, une avancée" },
      { en: "A trend", fr: "Une tendance" },
      { en: "An improvement", fr: "Une amélioration" },
      { en: "A step", fr: "Une étape" },
      { en: "A milestone", fr: "Une étape importante" },
      { en: "A watershed", fr: "Un tournant décisif" },
      { en: "A renewal", fr: "Un renouveau" },
      { en: "The duration", fr: "La durée" },
      { en: "A timeline", fr: "Une chronologie" },
      { en: "A delay", fr: "Un retard" },
      { en: "Hindsight", fr: "Le recul" },
      { en: "A boom", fr: "Une période de prospérité" },
      { en: "An era / an age", fr: "Une ère, une époque" },
      { en: "A patent", fr: "Un brevet" },
      { en: "A rate", fr: "Un taux" },
      { en: "An event", fr: "Un évènement" },
      { en: "A memory", fr: "Un souvenir" },
      { en: "A reminder", fr: "Un rappel" },
      { en: "The aftermath", fr: "Les suites, les répercussions" }
    ]
  },
  {
    id: "justice",
    title: "La justice",
    words: [
      { en: "The court", fr: "Le tribunal" },
      { en: "A case", fr: "Une affaire" },
      { en: "A hearing", fr: "Une audition" },
      { en: "A lawsuit", fr: "Une action en justice" },
      { en: "A trial", fr: "Un procès" },
      { en: "A judge", fr: "Un juge" },
      { en: "The charges", fr: "Les charges, les chefs d'accusation" },
      { en: "The defendant", fr: "Le prévenu" },
      { en: "The plaintiff", fr: "Le plaignant" },
      { en: "An attorney / a lawyer", fr: "Un avocat" },
      { en: "Evidence", fr: "Une preuve" },
      { en: "A witness", fr: "Un témoin" },
      { en: "A testimony", fr: "Un témoignage" },
      { en: "A bail", fr: "Une caution" },
      { en: "Parole", fr: "Liberté conditionnelle" },
      { en: "Guilt", fr: "La culpabilité" },
      { en: "Appeal", fr: "Un appel" },
      { en: "A pardon", fr: "Une grâce" },
      { en: "A criminal record", fr: "Un casier judiciaire" }
    ]
  },
  {
    id: "loi",
    title: "La loi",
    words: [
      { en: "A bill", fr: "Un projet de loi" },
      { en: "A law / an act", fr: "Une loi" },
      { en: "An executive order", fr: "Un décret présidentiel" },
      { en: "The rule of law", fr: "L'état de droit" },
      { en: "A veto", fr: "Un véto" },
      { en: "A complaint", fr: "Une plainte" },
      { en: "An investigation", fr: "Une enquête" },
      { en: "(in) custody", fr: "(en) garde à vue" },
      { en: "Law enforcement", fr: "Le maintien de l'ordre" },
      { en: "A felony", fr: "Un crime" },
      { en: "A felon", fr: "Un criminel" },
      { en: "A thief", fr: "Un voleur" },
      { en: "A smuggler", fr: "Un contrebandier" },
      { en: "A crook / a con man", fr: "Un escroc" },
      { en: "A burglar", fr: "Un cambrioleur" },
      { en: "Money laundering", fr: "Le blanchiment d'argent" },
      { en: "Tax evasion", fr: "La fraude fiscale" },
      { en: "A convict", fr: "Un condamné" },
      { en: "An inmate", fr: "Un détenu" },
      { en: "Jail / prison", fr: "La prison" }
    ]
  },
  {
    id: "violence-paix",
    title: "La violence et la paix",
    words: [
      { en: "A terrorist attack", fr: "Un attentat" },
      { en: "A suicide bomber", fr: "Un kamikaze" },
      { en: "The casualties", fr: "Les pertes" },
      { en: "An injury / a wound", fr: "Une blessure" },
      { en: "The military", fr: "L'armée" },
      { en: "The troops", fr: "Les troupes" },
      { en: "The rank and file", fr: "Les troupes (péjoratif)" },
      { en: "A soldier / a private", fr: "Un soldat" },
      { en: "Cannon fodder", fr: "De la chair à canon" },
      { en: "A slaughter", fr: "Un massacre" },
      { en: "A shelter", fr: "Un abri, un refuge" },
      { en: "An ally", fr: "Un allié" },
      { en: "The civilians", fr: "Les civils" },
      { en: "Draft / conscription", fr: "La conscription" },
      { en: "A ceasefire", fr: "Un cessez-le-feu" },
      { en: "Weapons of Mass Destruction (WMDs)", fr: "Armes de destruction massives" },
      { en: "Nuclear firepower", fr: "La puissance nucléaire" },
      { en: "A blockade", fr: "Un blocus" }
    ]
  },
  {
    id: "elections",
    title: "Les élections",
    words: [
      { en: "Franchise / suffrage", fr: "Le droit de vote" },
      { en: "A platform", fr: "Un programme électoral" },
      { en: "A manifesto", fr: "Une profession de foi" },
      { en: "A rally", fr: "Un meeting de campagne" },
      { en: "A constituency", fr: "Une circonscription" },
      { en: "A voter", fr: "Un électeur" },
      { en: "The electorate", fr: "L'électorat" },
      { en: "The grassroots", fr: "L'électorat de base" },
      { en: "A poll", fr: "Un sondage" },
      { en: "The turnout", fr: "La participation" },
      { en: "The ballot", fr: "Le bulletin de vote" },
      { en: "A ballot box", fr: "Une urne" },
      { en: "Ballot box stuffing", fr: "Le bourrage des urnes" },
      { en: "Ballot rigging", fr: "La fraude électorale" },
      { en: "(By) proxy", fr: "(Par) procuration" },
      { en: "Postal vote / absentee ballot", fr: "Vote par correspondance" },
      { en: "Blank vote", fr: "Vote blanc" },
      { en: "A landslide victory", fr: "Une victoire écrasante" },
      { en: "The run-off (election)", fr: "Le second tour" },
      { en: "The nominee", fr: "Le candidat investi" }
    ]
  },
  {
    id: "environnement",
    title: "L'environnement",
    words: [
      { en: "An environmentalist", fr: "Un défenseur de l'environnement" },
      { en: "Carbon dioxide", fr: "Le dioxyde de carbone" },
      { en: "Greenhouse gases", fr: "Les gaz à effet de serre" },
      { en: "The carbon footprint", fr: "L'empreinte carbone" },
      { en: "A windmill", fr: "Une éolienne" },
      { en: "Waste", fr: "Les déchets" },
      { en: "Garbage / trash", fr: "Des détritus" },
      { en: "The soil", fr: "Le sol" },
      { en: "Resources", fr: "Les ressources" },
      { en: "Exhaustion", fr: "L'épuisement" },
      { en: "A shortage", fr: "Une pénurie" },
      { en: "A chemical", fr: "Un produit chimique" },
      { en: "A fertilizer", fr: "Un engrais" },
      { en: "Drought", fr: "La sécheresse" },
      { en: "A flood", fr: "Une inondation" },
      { en: "An endangered species", fr: "Une espèce en voie de disparition" },
      { en: "Global warming", fr: "Le réchauffement planétaire" },
      { en: "Climate change", fr: "Le changement climatique" },
      { en: "The sea level", fr: "Le niveau de la mer" },
      { en: "Sustainability", fr: "La durabilité" }
    ]
  }
];
